
CUPTI_PFN_DECL(cuptiActivityEnable, CUpti_ActivityKind)
CUPTI_PFN_DECL(cuptiActivityFlush, CUcontext, uint32_t, uint32_t)
CUPTI_PFN_DECL(cuptiActivityFlushAll, uint32_t)
CUPTI_PFN_DECL(cuptiActivityGetAttribute, CUpti_ActivityAttribute, size_t*, void*)
CUPTI_PFN_DECL(cuptiActivityGetNextRecord,  uint8_t*, size_t,  CUpti_Activity**)
CUPTI_PFN_DECL(cuptiActivityGetNumDroppedRecords,  CUcontext, uint32_t, size_t*)
CUPTI_PFN_DECL(cuptiActivitySetAttribute,  CUpti_ActivityAttribute, size_t*, void*)
CUPTI_PFN_DECL(cuptiActivityRegisterCallbacks, CUpti_BuffersCallbackRequestFunc , CUpti_BuffersCallbackCompleteFunc)
CUPTI_PFN_DECL(cuptiDeviceGetTimestamp, CUcontext,  uint64_t*)
CUPTI_PFN_DECL(cuptiEnableDomain, uint32_t,  CUpti_SubscriberHandle, CUpti_CallbackDomain )
CUPTI_PFN_DECL(cuptiGetResultString, CUptiResult result, const char** str)
CUPTI_PFN_DECL(cuptiGetTimestamp, uint64_t*)
CUPTI_PFN_DECL(cuptiActivityPushExternalCorrelationId, CUpti_ExternalCorrelationKind, uint64_t)
CUPTI_PFN_DECL(cuptiActivityPopExternalCorrelationId, CUpti_ExternalCorrelationKind, uint64_t *)
